all:
  vars:
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client_1:
       ansible_host: 192.168.99.11
    client_2:
       ansible_host: 192.168.99.12
  vars:
    env: production
    ansible_password: admin123