# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 2048
CPU = 2

Vagrant.configure("2") do |config|
  config.vm.define "docker-ubuntu" do |docker|
    docker-ubuntu.vm.box = "ubuntu/xenial64"
    docker-ubuntu.vm.network "private_network", type: "dhcp"
	  docker.vm.hostname = "docker-ubuntu"
    docker-ubuntu.vm.provider "virtualbox" do |v|
  	  v.name = "docker-ubuntu"
  	  v.memory = RAM
  	  v.cpus = CPU
  	end
  	docker-ubuntu.vm.provision :shell do |shell|
  	  shell.path = "install_docker.sh"
    end 
  end
end