# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 4096
CPU = 2
IP = "172.28.128.7"

Vagrant.configure("2") do |config|
  config.vm.define "ubdocker" do |ubdocker|
    ubdocker.vm.box = "v0rtex/xenial64"
    ubdocker.vm.network "private_network", ip: IP
	  ubdocker.vm.hostname = "ubdocker"
    ubdocker.vm.provider "virtualbox" do |v|
  	  v.name = "ubdocker"
  	  v.memory = RAM
  	  v.cpus = CPU
	    v.gui = false
  	end
  	ubdocker.vm.provision :shell do |shell|
  	  shell.path = "install_docker.sh"
    end 
  end
end