# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 2048
CPU = 2

Vagrant.configure("2") do |config|
  config.vm.define "dockercompose" do |dockercompose|
    dockercompose.vm.box = "ubuntu/xenial64"
    dockercompose.vm.network "private_network", type: "dhcp"
	  dockercompose.vm.hostname = "dockercompose"
    dockercompose.vm.provider "virtualbox" do |v|
  	  v.name = "dockercompose"
  	  v.memory = RAM
  	  v.cpus = CPU
  	end
  	dockercompose.vm.provision :shell do |shell|
  	  shell.path = "install_docker.sh"
    end 
  end
end