# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_IMAGE = "geerlingguy/centos7"
BOX_VERSION = "1.2.25"
MEMORY = "2048"
CPU = "2"
HOST = "localhost"
IP_NODE1 = "10.0.5.11"
IP_NODE2 = "10.0.5.12"
IP_NODE3 = "10.0.5.13"
NODE1 = "node-elk1"
NODE2 = "node-elk2"
NODE3 = "node-kibana"

Vagrant.configure("2") do |config|
  # port forwarding
  config.vm.network "forwarded_port", guest: 9200, host: 9200 # ES
  config.vm.network "forwarded_port", guest: 5601, host: 5601 # Kibana
  config.vm.network "forwarded_port", guest: 8111, host: 8111 # HTTP server
  config.vm.define NODE1 do |subconfig|
    subconfig.vm.box = BOX_IMAGE
	subconfig.vm.box_version = BOX_VERSION
	subconfig.vbguest.auto_update = false
    subconfig.vm.hostname = NODE1
	subconfig.vm.network :private_network, ip: IP_NODE1
	subconfig.vm.synced_folder "./", "/vagrant"
	#Make some changes to the elasticsearch.yml file and start the service
	subconfig.vm.provision "shell",
      inline: <<-SHELL
	    sudo echo "[*] Installing Elastic Search"
        sudo sed -i 's/#cluster.name: my-application/cluster.name: ElasticserchCluster/g' /etc/elasticsearch/elasticsearch.yml
		sudo sed -i 's/#node.name: node-1/node.name: node-elk1/g' /etc/elasticsearch/elasticsearch.yml
		sudo sed -i 's/#network.host: 192.168.0.1/network.host: ["10.0.5.11", "localhost"]/g' /etc/elasticsearch/elasticsearch.yml
		sudo echo 'discovery.seed_hosts: ["10.0.5.11", "10.0.5.12", "10.0.5.13"]' >>  /etc/elasticsearch/elasticsearch.yml
		sudo echo 'cluster.initial_master_nodes: ["10.0.5.11", "10.0.5.12"]' >>  /etc/elasticsearch/elasticsearch.yml
		sudo echo 'node.master: true' >>  /etc/elasticsearch/elasticsearch.yml
		sudo echo 'node.data: false' >>  /etc/elasticsearch/elasticsearch.yml
		sudo echo -e "\e[1;31mElasticsearch needs some time to start so please be patient...\e[0m"
		sudo /bin/systemctl daemon-reload
		sudo /bin/systemctl enable elasticsearch.service
		sudo /bin/systemctl start elasticsearch.service
		sudo echo "[+] Done Installing Elastic Search"
	  SHELL
	subconfig.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", MEMORY]
          vb.customize ["modifyvm", :id, "--cpus", CPU]
		  vb.customize ["modifyvm", :id, "--name", NODE1]
	end
  end
  config.vm.define NODE2 do |subconfig|
    subconfig.vm.box = BOX_IMAGE
	subconfig.vm.box_version = BOX_VERSION
	subconfig.vbguest.auto_update = false
    subconfig.vm.hostname = NODE2
	subconfig.vm.network :private_network, ip: IP_NODE2
	subconfig.vm.network "forwarded_port", guest: 9300, host: 9300 # ES
	subconfig.vm.synced_folder "./", "/vagrant"
	#Make some changes to the elasticsearch.yml file and start the service
	subconfig.vm.provision "shell",
      inline: <<-SHELL
	    sudo echo "[*] Installing Elastic Search"
		sudo sed -i 's/#cluster.name: my-application/cluster.name: ElasticserchCluster/g' /etc/elasticsearch/elasticsearch.yml
		sudo sed -i 's/#node.name: node-1/node.name: node-elk2/g' /etc/elasticsearch/elasticsearch.yml
		sudo sed -i 's/#network.host: 192.168.0.1/network.host: ["10.0.5.12", "localhost"]/g' /etc/elasticsearch/elasticsearch.yml
		sudo echo 'discovery.seed_hosts: ["10.0.5.11", "10.0.5.12", "10.0.5.13"]' >>  /etc/elasticsearch/elasticsearch.yml
		sudo echo 'cluster.initial_master_nodes: ["10.0.5.11", "10.0.5.12"]' >>  /etc/elasticsearch/elasticsearch.yml
		sudo echo 'node.master: true' >>  /etc/elasticsearch/elasticsearch.yml
		sudo echo -e "\e[1;31mElasticsearch needs some time to start so please be patient...\e[0m"
		sudo /bin/systemctl enable elasticsearch.service
		sudo /bin/systemctl start elasticsearch.service
		sudo echo "[+] Done Installing Elastic Search"
	  SHELL
	subconfig.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", MEMORY]
          vb.customize ["modifyvm", :id, "--cpus", CPU]
		  vb.customize ["modifyvm", :id, "--name", NODE2]
	end
  end
  config.vm.define NODE3 do |subconfig|
    subconfig.vm.box = BOX_IMAGE
	subconfig.vm.box_version = BOX_VERSION
	subconfig.vbguest.auto_update = false
    subconfig.vm.hostname = NODE3
	subconfig.vm.network :private_network, ip: IP_NODE3
	subconfig.vm.synced_folder "./", "/vagrant"
	#Make some changes to the elasticsearch.yml file and start the service
	subconfig.vm.provision "shell",
      inline: <<-SHELL
	    sudo echo "[*] Installing Kibana"
		sudo sed -i 's/#cluster.name: my-application/cluster.name: ElasticserchCluster/g' /etc/elasticsearch/elasticsearch.yml
		sudo sed -i 's/#node.name: node-1/node.name: node-kibana/g' /etc/elasticsearch/elasticsearch.yml
		sudo sed -i 's/#network.host: 192.168.0.1/network.host: ["10.0.5.13", "localhost"]/g' /etc/elasticsearch/elasticsearch.yml
		sudo echo 'discovery.seed_hosts: ["10.0.5.11", "10.0.5.12", "10.0.5.13"]' >>  /etc/elasticsearch/elasticsearch.yml
		sudo echo 'cluster.initial_master_nodes: ["10.0.5.11", "10.0.5.12"]' >>  /etc/elasticsearch/elasticsearch.yml
		sudo echo 'node.master: true' >>  /etc/elasticsearch/elasticsearch.yml			
		sudo systemctl start elasticsearch.service
		sudo echo -e "\e[1;31mKibana needs some time to start so please be patient...\e[0m"
	    sudo wget https://artifacts.elastic.co/downloads/kibana/kibana-7.15.2-x86_64.rpm
        shasum -a 512 kibana-7.15.2-x86_64.rpm 
        sudo rpm --install kibana-7.15.2-x86_64.rpm
		sudo sed -i 's/#server.port: 5601/server.port: 5601/g' /etc/kibana/kibana.yml
		sudo sed -i 's/#server.host: "localhost"/server.host: "10.0.5.13"/g' /etc/kibana/kibana.yml
		sudo sed -i 's/#server.name: "your-hostname"/server.name: "kibana"/g' /etc/kibana/kibana.yml
		sudo echo -e "\e[1;31mElasticsearch needs some time to start so please be patient...\e[0m"
		sudo /bin/systemctl daemon-reload
		sudo /bin/systemctl enable kibana.service
		sudo /bin/systemctl start kibana.service
		sudo echo "[*] Done Installing Kibana"
	  SHELL
	subconfig.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", MEMORY]
          vb.customize ["modifyvm", :id, "--cpus", CPU]
		  vb.customize ["modifyvm", :id, "--name", NODE3]
	end
  end
  # Install Elasticsearch on all machines and install some extra additional packages 
  config.vm.provision "shell", inline: <<-SHELL
	sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
    sudo /bin/systemctl restart sshd.service
	sudo yum -y install zip unzip git apt-transport-https default-jre vim nmap net-tools htop
	sudo wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm
	sudo wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-x86_64.rpm.sha512
	shasum -a 512 -c elasticsearch-7.15.2-x86_64.rpm.sha512 
	sudo rpm --install elasticsearch-7.15.2-x86_64.rpm
	sudo /bin/systemctl daemon-reload
	sudo /bin/systemctl enable elasticsearch.service
  SHELL
end