# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 2048
CPU = 1
IP1 = "10.0.0.1"
IP2 = "10.0.0.2"

Vagrant.configure("2") do |config|
  # Configure Manager Docker-Swarm
  config.vm.define "masterswarm" do |masterswarm|
    masterswarm.vm.box = "ubuntu/xenial64"
    masterswarm.vm.network "private_network", ip: IP1
	  masterswarm.vm.hostname = "masterswarm"
    masterswarm.vm.provider "virtualbox" do |v|
	  v.name = "masterswarm"
  	  v.memory = RAM
  	  v.cpus = CPU
	end
    masterswarm.vm.provision :shell do |shell|
	  shell.path = "install_docker.sh"
	end
  end
  # Configure Worker Docker-Swarm
  config.vm.define "workerswarm1" do |workerswarm1|
    workerswarm1.vm.box = "ubuntu/xenial64"
    workerswarm1.vm.network "private_network", ip: IP2
	  workerswarm1.vm.hostname = "workerswarm1"
    workerswarm1.vm.provider "virtualbox" do |v|
	  v.name = "workerswarm1"
      v.memory = RAM
      v.cpus = CPU
    end
    workerswarm1.vm.provision :shell do |shell|
	  shell.path = "install_docker.sh"
    end 
  end
end
