   
all:
  hosts:
    192.168.99.11:
      ansible_user: admin 
      ansible_password: admin123
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    192.168.99.12:
      ansible_user: admin 
      ansible_password: admin123
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
