apiVersion: v1
kind: ServiceAccount
metadata:
  name: chris-sa
  namespace: kube-system
secrets:
  - name: chris-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chris
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces", "nodes"]
    verbs: ["create", "get", "update", "list", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployment"]
    verbs: ["create", "get", "update", "list", "delete", "watch", "patch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chris
subjects:
  - kind: ServiceAccount
    name: chris-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: chris
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: chris-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: chris-sa
type: kubernetes.io/service-account-token